export const IItem = {
    id: 0,
    title: '',
    disporder: 0,
    boardcode: '',
    projectcode: '',
    prioritycode: '',
    sizecode: '',
    statuscode: '',
    createdbyuser: '',
    createdtimestamp: '',
    assignedtouser: '',
    assignedtimestamp: '',
    closedbyuser: '',
    closedtimestamp: '',
    duedate: '',
    description: '',
    comments: '',
};
